name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'LICENSE-*'
      - '.gitignore'
      - 'cliff.toml'
      - 'azalea.schema.json'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'LICENSE-*'
      - '.gitignore'
      - 'cliff.toml'
      - 'azalea.schema.json'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.93.1
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: rui314/setup-mold@v1
      - uses: extractions/setup-just@v3
      - name: Clippy
        run: just clippy

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.93.1
      - uses: Swatinem/rust-cache@v2
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@nextest
      - uses: extractions/setup-just@v3
      - name: Test
        run: just test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
